import { createRequestHandler, type ServerBuild } from "react-router";
// Wrangler runs the custom build command before bundling this Worker, so the
// generated server build exists at deploy time even though it is gitignored.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - The module is generated by `react-router build`.
import * as serverBuild from "../build/server/index.js";

type HyperdriveBinding = {
  connectionString: string;
};

type CloudflareBindings = Record<string, unknown> & {
  HYPERDRIVE_CONNECTION_STRING?: string;
  HYPERDRIVE?: HyperdriveBinding;
};

const requestHandler = createRequestHandler(
  () => Promise.resolve(serverBuild as unknown as ServerBuild),
  typeof process !== "undefined" ? process.env.NODE_ENV ?? "production" : "production",
);

const worker = {
  async fetch(request: Request, env: CloudflareBindings, ctx: unknown) {
    const cloudflareRequest = request as Request & { cf?: unknown };

    if (!process.env.HYPERDRIVE_CONNECTION_STRING && env.HYPERDRIVE?.connectionString) {
      process.env.HYPERDRIVE_CONNECTION_STRING = env.HYPERDRIVE.connectionString;
    }

    return requestHandler(request, {
      cloudflare: {
        env,
        ctx,
        cf: cloudflareRequest.cf,
        caches,
      },
    });
  },
};

export default worker;
