// Wrangler bundles this shim, then resolves the generated React Router server
// build when the Worker lazily imports it after request-specific env setup.
/* eslint-disable import/no-unresolved */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Generated by `react-router build` during the deploy step.
import * as serverBuild from "../build/server/index.js";
/* eslint-enable import/no-unresolved */

export default serverBuild;
